spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tiago-oliveira89/ConfigData"
server:
  port: 8001

management.endpoints.web.exposure.include: health,info,bus-refresh